# Generated by Django 3.2 on 2022-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_pic', models.ImageField(upload_to='transfer')),
            ],
        ),
        migrations.CreateModel(
            name='RawPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_pic', models.ImageField(upload_to='transfer')),
                ('style', models.CharField(max_length=20)),
            ],
        ),
    ]
